return {
	"stevearc/conform.nvim",
	dependencies = { "mason.nvim" },
	cmd = "ConformInfo",
	opts = {
		formatters_by_ft = {
			["javascript"] = { "oxlint" },
			["javascriptreact"] = { "oxlint" },
			["typescript"] = { "oxlint" },
			["typescriptreact"] = { "oxlint" },
			["vue"] = { "prettier" },
			["css"] = { "prettier" },
			["scss"] = { "prettier" },
			["less"] = { "prettier" },
			["html"] = { "prettier" },
			["json"] = { "prettier" },
			["jsonc"] = { "prettier" },
			["yaml"] = { "prettier" },
			["markdown"] = { "prettier" },
			["markdown.mdx"] = { "prettier" },
			["graphql"] = { "prettier" },
			lua = { "stylua" },
		},
	},
}
